apiVersion: apps/v1beta1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: samplews-deployment
  labels:
    app: samplews
spec:
  replicas: 3
  selector:
    matchLabels:
      app: samplews
  template:
    metadata:
      labels:
        app: samplews
    spec:
      containers:
      - name: samplews
        image: gcr.io/denny-lab-1/samplews:v2
        ports:
        - containerPort: 8080